#include "config.hpp"
#include <cstdlib>
#include <mutex>
#include <stdexcept>
#include <iostream>

Config& Config::instance() {
    static Config instance;
    return instance;
}

Config::Config() {
    const char* home = std::getenv("HOME");
    if (home) {
        config_dir = std::string(home) + "/.config/high";
    } else {
        config_dir = "/etc/high";
    }
}

void Config::load_from_env() {
    std::lock_guard<std::mutex> lock(mutex);
    
    if (const char* env = std::getenv("LLM_API_BASE")) {
        api_base = env;
    }
    if (const char* env = std::getenv("LLM_CONFIG_DIR")) {
        config_dir = env;
    }
    if (const char* env = std::getenv("HTTP_PROXY")) {
        http_proxy = env;
    }
    if (const char* env = std::getenv("LLM_SYSTEM_ROLE")) {
        system_role = env;
    }
    if (const char* env = std::getenv("LLM_MAX_TOKENS")) {
        try {
            max_tokens = std::stoi(env);
        } catch (...) {}
    }
    if (const char* env = std::getenv("LLM_TEMPERATURE")) {
        try {
            temperature = std::stod(env);
        } catch (...) {}
    }
    if (const char* env = std::getenv("LLM_VERBOSE")) {
        verbose = (std::string(env) == "1" || std::string(env) == "true");
    }
    if (const char* env = std::getenv("LLM_FORMAT_MARKDOWN")) {
        format_markdown = (std::string(env) == "1" || std::string(env) == "true");
    }
    if (const char* env = std::getenv("LLM_RAW_OUTPUT")) {
        raw_output = (std::string(env) == "1" || std::string(env) == "true");
    }
    if (const char* env = std::getenv("LLM_TIMEOUT")) {
        try {
            timeout = std::stoi(env);
        } catch (...) {}
    }
    if (const char* env = std::getenv("HIGHLIGHT_THEME")) {
        highlight_theme = env;
    }
    if (const char* env = std::getenv("HIGHLIGHT_PREVIEW")) {
        preview_code_blocks = (std::string(env) == "1" || std::string(env) == "true");
    } else if (const char* env = std::getenv("HIGH_PREVIEW_CODE")) {
        preview_code_blocks = (std::string(env) == "1" || std::string(env) == "true");
    }
    if (const char* env = std::getenv("HIGH_MARKDOWN_SYNTAX")) {
        markdown_enabled_ = (std::string(env) == "1" || std::string(env) == "true");
    }
    if (const char* env = std::getenv("LLM_TAB_WIDTH")) {
        try {
            int w = std::stoi(env);
            if (w > 0 && w <= 16) {
                tab_width = w;
            }
        } catch (...) {}
    }
}

void Config::dump_as_env(std::ostream& out) const {
    std::lock_guard<std::mutex> lock(mutex);
    
    out << "# high configuration - add to ~/.bashrc or ~/.zshrc\n";
    out << "# Generated by: high --config-dump\n";
    out << "# Date: " << __DATE__ << " " << __TIME__ << "\n\n";
    
    out << "export LLM_API_BASE=\"" << api_base << "\"\n";
    out << "export LLM_CONFIG_DIR=\"" << config_dir << "\"\n";
    
    if (!http_proxy.empty()) {
        out << "export HTTP_PROXY=\"" << http_proxy << "\"\n";
    }
    
    if (system_role != "You are a helpful assistant.") {
        out << "export LLM_SYSTEM_ROLE=\"" << system_role << "\"\n";
    }
    
    if (max_tokens > 0) {
        out << "export LLM_MAX_TOKENS=" << max_tokens << "\n";
    }
    
    if (temperature != 1.0) {
        out << "export LLM_TEMPERATURE=" << temperature << "\n";
    }
    
    if (verbose) {
        out << "export LLM_VERBOSE=1\n";
    }
    
    if (format_markdown) {
        out << "export LLM_FORMAT_MARKDOWN=1\n";
    }
    
    if (raw_output) {
        out << "export LLM_RAW_OUTPUT=1\n";
    }
    
    if (timeout != 36000) {
        out << "export LLM_TIMEOUT=" << timeout << "\n";
    }
    
    if (highlight_theme != "xoria256") {
        out << "export HIGHLIGHT_THEME=\"" << highlight_theme << "\"\n";
    }
    
    if (preview_code_blocks) {
        out << "export HIGH_PREVIEW_CODE=1\n";
    }
    
    if (markdown_enabled_) {
        out << "export HIGH_MARKDOWN_SYNTAX=1\n";
    }
    
    if (tab_width != 8) {
        out << "export LLM_TAB_WIDTH=" << tab_width << "\n";
    }
    
    out << "\n# Aliases for common commands\n";
    out << "alias high-preview='high -p -f'\n";
    out << "alias high-raw='high -r'\n";
    out << "alias high-list='high -l'\n";
    out << "alias high-plain='high -F'\n";
}

std::string Config::get_api_base() const {
    std::lock_guard<std::mutex> lock(mutex);
    return api_base;
}

std::string Config::get_config_dir() const {
    std::lock_guard<std::mutex> lock(mutex);
    return config_dir;
}

std::string Config::get_http_proxy() const {
    std::lock_guard<std::mutex> lock(mutex);
    return http_proxy;
}

std::string Config::get_system_role() const {
    std::lock_guard<std::mutex> lock(mutex);
    return system_role;
}

int Config::get_max_tokens() const {
    std::lock_guard<std::mutex> lock(mutex);
    return max_tokens;
}

double Config::get_temperature() const {
    std::lock_guard<std::mutex> lock(mutex);
    return temperature;
}

bool Config::is_verbose() const {
    std::lock_guard<std::mutex> lock(mutex);
    return verbose;
}

bool Config::format_markdown_enabled() const {
    std::lock_guard<std::mutex> lock(mutex);
    return format_markdown;
}

bool Config::raw_output_enabled() const {
    std::lock_guard<std::mutex> lock(mutex);
    return raw_output;
}

int Config::get_timeout() const {
    std::lock_guard<std::mutex> lock(mutex);
    return timeout;
}

std::string Config::get_highlight_theme() const {
    std::lock_guard<std::mutex> lock(mutex);
    return highlight_theme;
}

bool Config::preview_enabled() const {
    std::lock_guard<std::mutex> lock(mutex);
    return preview_code_blocks;
}

bool Config::markdown_enabled() const {
    std::lock_guard<std::mutex> lock(mutex);
    return markdown_enabled_;
}

int Config::get_tab_width() const {
    std::lock_guard<std::mutex> lock(mutex);
    return tab_width;
}

void Config::set_api_base(const std::string& val) {
    std::lock_guard<std::mutex> lock(mutex);
    api_base = val;
}

void Config::set_http_proxy(const std::string& val) {
    std::lock_guard<std::mutex> lock(mutex);
    http_proxy = val;
}

void Config::set_system_role(const std::string& val) {
    std::lock_guard<std::mutex> lock(mutex);
    system_role = val;
}

void Config::set_max_tokens(int val) {
    std::lock_guard<std::mutex> lock(mutex);
    max_tokens = val;
}

void Config::set_verbose(bool val) {
    std::lock_guard<std::mutex> lock(mutex);
    verbose = val;
}

void Config::set_format_markdown(bool val) {
    std::lock_guard<std::mutex> lock(mutex);
    format_markdown = val;
}

void Config::set_raw_output(bool val) {
    std::lock_guard<std::mutex> lock(mutex);
    raw_output = val;
}

void Config::set_highlight_theme(const std::string& theme) {
    std::lock_guard<std::mutex> lock(mutex);
    if (!theme.empty()) highlight_theme = theme;
}

void Config::set_preview_enabled(bool val) {
    std::lock_guard<std::mutex> lock(mutex);
    preview_code_blocks = val;
}

void Config::set_markdown_enabled(bool val) {
    std::lock_guard<std::mutex> lock(mutex);
    markdown_enabled_ = val;
}

void Config::set_tab_width(int val) {
    std::lock_guard<std::mutex> lock(mutex);
    if (val > 0 && val <= 16) tab_width = val;
}
